<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup>  <UserSecretsId>11d89703-8c4a-40a6-89e2-5311bb87cbf9</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ticketing.Application\Ticketing.Application.csproj" />
    <ProjectReference Include="..\Ticketing.Infrastructure\Ticketing.Infrastructure.csproj" />
  </ItemGroup>

</Project>
