// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ticketing.Infrastructure.Persistence;

#nullable disable

namespace Ticketing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TicketingDbContext))]
    [Migration("20260907141417_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ticketing.Domain.Booking.SeatHold", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int>("PerformanceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "PerformanceId")
                        .HasName("UQ_SeatHolds_IdPerformance");

                    b.HasAlternateKey("Id", "BuyerId", "PerformanceId")
                        .HasName("UQ_SeatHolds_IdBuyerPerformance");

                    b.HasIndex("PerformanceId");

                    b.HasIndex("BuyerId", "PerformanceId")
                        .IsUnique()
                        .HasDatabaseName("UX_SeatHolds_ActiveBuyerPerformance")
                        .HasFilter("[Status] = 'Active'");

                    b.ToTable("SeatHolds", null, t =>
                        {
                            t.HasCheckConstraint("CK_SeatHolds_Amount", "[TotalAmount] > 0");

                            t.HasCheckConstraint("CK_SeatHolds_Expiry", "[ExpiresAtUtc] > [CreatedAtUtc]");

                            t.HasCheckConstraint("CK_SeatHolds_Status", "[Status] IN ('Active','Completed','Cancelled','Expired')");
                        });
                });

            modelBuilder.Entity("Ticketing.Domain.Catalog.Event", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Performer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Events_Code");

                    b.ToTable("Events", null, t =>
                        {
                            t.HasCheckConstraint("CK_Events_Category", "[Category] IN ('Concert','Sport')");
                        });
                });

            modelBuilder.Entity("Ticketing.Domain.Catalog.Performance", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSalesPaused")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("SalesClosesAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("SalesOpensAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_Performances");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("EventId");

                    b.ToTable("Performances", null, t =>
                        {
                            t.HasCheckConstraint("CK_Performances_Duration", "[DurationMinutes] > 0");

                            t.HasCheckConstraint("CK_Performances_Times", "[SalesOpensAtUtc] < [SalesClosesAtUtc] AND [SalesClosesAtUtc] < [StartsAtUtc]");
                        });
                });

            modelBuilder.Entity("Ticketing.Domain.Catalog.Seat", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("HeldUntilUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("HoldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PerformanceId")
                        .HasColumnType("int");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.HasKey("Id");

                    b.HasIndex("HoldId")
                        .HasDatabaseName("IX_Seats_HoldId");

                    b.HasIndex("HoldId", "PerformanceId");

                    b.HasIndex("SectionId", "PerformanceId");

                    b.HasIndex("PerformanceId", "SectionId", "RowNumber", "SeatNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_Seats_Address");

                    b.ToTable("Seats", null, t =>
                        {
                            t.HasCheckConstraint("CK_Seats_Number", "[RowNumber] > 0 AND [SeatNumber] > 0");

                            t.HasCheckConstraint("CK_Seats_State", "    ([Status] = 'Available' AND [HoldId] IS NULL     AND [HeldUntilUtc] IS NULL)\n OR ([Status] = 'Held'      AND [HoldId] IS NOT NULL AND [HeldUntilUtc] IS NOT NULL)\n OR ([Status] = 'Sold'      AND [HoldId] IS NOT NULL AND [HeldUntilUtc] IS NULL)");
                        });
                });

            modelBuilder.Entity("Ticketing.Domain.Catalog.Section", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("PerformanceId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RowCount")
                        .HasColumnType("int");

                    b.Property<int>("SeatsPerRow")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "PerformanceId")
                        .HasName("UQ_Sections_IdPerformance");

                    b.HasIndex("PerformanceId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Sections_PerformanceCode");

                    b.ToTable("Sections", null, t =>
                        {
                            t.HasCheckConstraint("CK_Sections_Code", "[Code] IN ('A','B','C')");

                            t.HasCheckConstraint("CK_Sections_Values", "[Price] > 0 AND [RowCount] > 0 AND [SeatsPerRow] > 0");
                        });
                });

            modelBuilder.Entity("Ticketing.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasDefaultValue("TWD")
                        .IsFixedLength();

                    b.Property<string>("EventTitleSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("HoldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PerformanceId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartsAtSnapshot")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("HoldId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Orders_Hold");

                    b.HasIndex("PerformanceId");

                    b.HasIndex("BuyerId", "PerformanceId")
                        .HasDatabaseName("IX_Orders_BuyerPerformance");

                    b.HasIndex("BuyerId", "CreatedAtUtc", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("IX_Orders_Buyer");

                    b.HasIndex("HoldId", "BuyerId", "PerformanceId");

                    b.ToTable("Orders", null, t =>
                        {
                            t.HasCheckConstraint("CK_Orders_Amount", "[TotalAmount] > 0 AND [Currency] = 'TWD'");
                        });
                });

            modelBuilder.Entity("Ticketing.Domain.Users.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("GoogleSubject")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_AppUsers_Email");

                    b.HasIndex("GoogleSubject")
                        .IsUnique()
                        .HasDatabaseName("UX_AppUsers_GoogleSubject")
                        .HasFilter("[GoogleSubject] IS NOT NULL");

                    b.ToTable("AppUsers", null, t =>
                        {
                            t.HasCheckConstraint("CK_AppUsers_Identity", "[PasswordHash] IS NOT NULL OR [GoogleSubject] IS NOT NULL");

                            t.HasCheckConstraint("CK_AppUsers_Role", "[Role] IN ('Customer','Admin')");
                        });
                });

            modelBuilder.Entity("Ticketing.Infrastructure.Persistence.Entities.AdminAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RequestHash")
                        .HasColumnType("binary(32)");

                    b.Property<string>("ResultJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasDatabaseName("UX_AdminAudits_OperationId")
                        .HasFilter("[OperationId] IS NOT NULL");

                    b.ToTable("AdminAudits", null, t =>
                        {
                            t.HasCheckConstraint("CK_AdminAudits_Operation", "    ([OperationId] IS NULL     AND [RequestHash] IS NULL     AND [ResultJson] IS NULL)\n OR ([OperationId] IS NOT NULL AND [RequestHash] IS NOT NULL AND [ResultJson] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Ticketing.Infrastructure.Persistence.Entities.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int>("HttpStatus")
                        .HasColumnType("int");

                    b.Property<byte[]>("RequestHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BuyerId", "Key");

                    b.ToTable("IdempotencyRecords", (string)null);
                });

            modelBuilder.Entity("Ticketing.Domain.Booking.SeatHold", b =>
                {
                    b.HasOne("Ticketing.Domain.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_SeatHolds_Buyer");

                    b.HasOne("Ticketing.Domain.Catalog.Performance", null)
                        .WithMany()
                        .HasForeignKey("PerformanceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_SeatHolds_Performance");

                    b.OwnsMany("Ticketing.Domain.Booking.SeatHoldItem", "_items", b1 =>
                        {
                            b1.Property<Guid>("HoldId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("SeatId")
                                .HasColumnType("int");

                            b1.Property<int>("RowNumber")
                                .HasColumnType("int");

                            b1.Property<int>("SeatNumber")
                                .HasColumnType("int");

                            b1.Property<string>("SectionCode")
                                .IsRequired()
                                .HasMaxLength(1)
                                .IsUnicode(false)
                                .HasColumnType("varchar(1)");

                            b1.Property<decimal>("UnitPrice")
                                .HasColumnType("decimal(10,2)");

                            b1.HasKey("HoldId", "SeatId");

                            b1.HasIndex("SeatId");

                            b1.ToTable("SeatHoldItems", null, t =>
                                {
                                    t.HasCheckConstraint("CK_SeatHoldItems_Values", "[RowNumber] > 0 AND [SeatNumber] > 0 AND [UnitPrice] > 0");
                                });

                            b1.WithOwner()
                                .HasForeignKey("HoldId");

                            b1.HasOne("Ticketing.Domain.Catalog.Seat", null)
                                .WithMany()
                                .HasForeignKey("SeatId")
                                .OnDelete(DeleteBehavior.NoAction)
                                .IsRequired()
                                .HasConstraintName("FK_SeatHoldItems_Seat");
                        });

                    b.Navigation("_items");
                });

            modelBuilder.Entity("Ticketing.Domain.Catalog.Performance", b =>
                {
                    b.HasOne("Ticketing.Domain.Catalog.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Performances_Event");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Ticketing.Domain.Catalog.Seat", b =>
                {
                    b.HasOne("Ticketing.Domain.Catalog.Performance", null)
                        .WithMany()
                        .HasForeignKey("PerformanceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Seats_Performance");

                    b.HasOne("Ticketing.Domain.Booking.SeatHold", null)
                        .WithMany()
                        .HasForeignKey("HoldId", "PerformanceId")
                        .HasPrincipalKey("Id", "PerformanceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Seats_HoldPerformance");

                    b.HasOne("Ticketing.Domain.Catalog.Section", null)
                        .WithMany()
                        .HasForeignKey("SectionId", "PerformanceId")
                        .HasPrincipalKey("Id", "PerformanceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Seats_SectionPerformance");
                });

            modelBuilder.Entity("Ticketing.Domain.Catalog.Section", b =>
                {
                    b.HasOne("Ticketing.Domain.Catalog.Performance", null)
                        .WithMany()
                        .HasForeignKey("PerformanceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Sections_Performance");
                });

            modelBuilder.Entity("Ticketing.Domain.Orders.Order", b =>
                {
                    b.HasOne("Ticketing.Domain.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Buyer");

                    b.HasOne("Ticketing.Domain.Catalog.Performance", null)
                        .WithMany()
                        .HasForeignKey("PerformanceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Performance");

                    b.HasOne("Ticketing.Domain.Booking.SeatHold", null)
                        .WithMany()
                        .HasForeignKey("HoldId", "BuyerId", "PerformanceId")
                        .HasPrincipalKey("Id", "BuyerId", "PerformanceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Orders_HoldBuyerPerformance");

                    b.OwnsMany("Ticketing.Domain.Orders.OrderItem", "_items", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("SeatId")
                                .HasColumnType("int");

                            b1.Property<int>("RowNumber")
                                .HasColumnType("int");

                            b1.Property<int>("SeatNumber")
                                .HasColumnType("int");

                            b1.Property<string>("SectionCode")
                                .IsRequired()
                                .HasMaxLength(1)
                                .IsUnicode(false)
                                .HasColumnType("varchar(1)");

                            b1.Property<string>("TicketCode")
                                .IsRequired()
                                .HasMaxLength(40)
                                .IsUnicode(false)
                                .HasColumnType("varchar(40)");

                            b1.Property<decimal>("UnitPrice")
                                .HasColumnType("decimal(10,2)");

                            b1.HasKey("OrderId", "SeatId");

                            b1.HasIndex("SeatId")
                                .IsUnique()
                                .HasDatabaseName("UQ_OrderItems_Seat");

                            b1.HasIndex("TicketCode")
                                .IsUnique()
                                .HasDatabaseName("UQ_OrderItems_Ticket");

                            b1.ToTable("OrderItems", null, t =>
                                {
                                    t.HasCheckConstraint("CK_OrderItems_Values", "[RowNumber] > 0 AND [SeatNumber] > 0 AND [UnitPrice] > 0");
                                });

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.HasOne("Ticketing.Domain.Catalog.Seat", null)
                                .WithMany()
                                .HasForeignKey("SeatId")
                                .OnDelete(DeleteBehavior.NoAction)
                                .IsRequired()
                                .HasConstraintName("FK_OrderItems_Seat");
                        });

                    b.Navigation("_items");
                });

            modelBuilder.Entity("Ticketing.Infrastructure.Persistence.Entities.IdempotencyRecord", b =>
                {
                    b.HasOne("Ticketing.Domain.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Idem_Buyer");
                });
#pragma warning restore 612, 618
        }
    }
}
